### ISSUE TITLE
Device service profile does not exist

### ISSUE THREAD

**Issue by danielnjx** [edgexfoundry-holding/device-opcua-go#3]
Log:
> daniel@dan-UbuntuVM:~/go/src/github.com/edgexfoundry/device-opcua-go$ make run
cd bin && ./edgex-launch.sh
Init: useRegistry:  profile:  confDir: 
Loading configuration from: /home/daniel/go/src/github.com/edgexfoundry/device-opcua-go/cmd/res/configuration.toml

> Bypassing registration in registry...
Calling service.Start.
EnableRemote is false, using local log file
level=INFO ts=2020-03-17T07:38:34.586310732Z app=edgex-device-opcua source=init.go:137 msg="Check Metadata service's status ..."
level=INFO ts=2020-03-17T07:38:34.586395633Z app=edgex-device-opcua source=init.go:137 msg="Check Data service's status ..."
level=INFO ts=2020-03-17T07:38:34.592815784Z app=edgex-device-opcua source=init.go:47 msg="Service clients initialize successful."
level=INFO ts=2020-03-17T07:38:34.604055473Z app=edgex-device-opcua source=service.go:149 msg="Device Service edgex-device-opcua exists"
level=ERROR ts=2020-03-17T07:38:34.611569533Z app=edgex-device-opcua source=devices.go:43 msg="Device Profile Prosys OPC-UA Simulation Server - Profile doesn't exist for Device Prosys OPC-UA Simulation Server"
level=ERROR ts=2020-03-17T07:38:34.615266262Z app=edgex-device-opcua source=devices.go:31 msg="creating Device from config failed: Prosys OPC-UA Simulation Server"
error: Failed to create the pre-defined Devices
^CMakefile:34: recipe for target 'run' failed
make: *** [run] Interrupt```

I've been trying to get the OPC-UA device service started but I always encounter the "Profile doesn't exist" error. 

Any ideas? Thank you so much.

**Comment by xuexiqiangzhe** [comment]
me,too
