### ISSUE TITLE
Upgrade for compatibility with EdgeX Foundry 2.x

### ISSUE THREAD

**Issue by jrtitus** [edgexfoundry-holding/device-opcua-go#8]
For a recent task that I was working on for my job, it was important that we have a device-opcua connector compatible with EdgeX Foundry 2.x (Ireland). I was able to upgrade and refactor the code in this repository to make it work and would like to share it back with the EdgeX community. 

The code can be found [here](https://github.com/SE-I-T-Digital/device-opcua-go/tree/ireland-dev), and I will create a PR in this repo. Please feel free to comment and make suggestions.

A short list of modifications & improvements:
- Upgrade to `v2` packages
- Code organization for read handlers, write handlers, and configuration
- Ability to subscribe to multiple resources
- Ability to write configuration from consul to change subscriptions
- Ability to trigger OPC UA method calls
- Unit test coverage
   ```
   $ go test ./... -cover
   ?       github.com/edgexfoundry/device-opcua-go [no test files]
   ?       github.com/edgexfoundry/device-opcua-go/cmd     [no test files]
   ok      github.com/edgexfoundry/device-opcua-go/internal/config 0.011s  coverage: 100.0% of statements
   ok      github.com/edgexfoundry/device-opcua-go/internal/driver 2.724s  coverage: 71.3% of statements
   ?       github.com/edgexfoundry/device-opcua-go/internal/test   [no test files]
   ```

Please let me know if there is anything else that is needed. Thank you!

**Comment by iain-anderson** [comment]
Closed via #9
